apiVersion: v1
appVersion: "1.0"
description: A Senzing configuration micro service.
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
 - configuration
name: senzing-configurator
sources:
 - https://github.com/Senzing/configurator
version: 1.0.0
