apiVersion: v1
appVersion: "1.0"
description: A Senzing environment for debugging
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
 - debug
name: senzing-debug
sources:
 - https://github.com/Senzing/docker-senzing-debug
version: 0.2.0
