apiVersion: v1
appVersion: "1.0"
description: A generator of Senzing data to feed Kafka
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
 - kafka
name: senzing-mock-data-generator
sources:
 - https://github.com/Senzing/mock-data-generator
version: 1.0.3
