apiVersion: v1
appVersion: "1.0"
description: A Senzing environment for ephemeral entity resolution.
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
name: resolver
sources:
 - https://github.com/Senzing/resolver
version: 1.1.1
