apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "senzing-stream-loader.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "senzing-stream-loader.name" . }}
    helm.sh/chart: {{ include "senzing-stream-loader.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "senzing-stream-loader.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "senzing-stream-loader.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: data    
      volumes:
        - name: opt-senzing-2
          hostPath:
            path: /opt/senzing
            type: DirectoryOrCreate
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: opt-senzing
              mountPath: /opt/senzing
          command:
            - /app/docker-entrypoint.sh
            - /app/stream-loader.py          
          env:
            - name: SENZING_KAFKA_BOOTSTRAP_SERVER
              value: "{{ .Values.senzing.kafkaBootstrapServerHost }}:{{ .Values.senzing.kafkaBootstrapServerPort }}"
            - name: SENZING_SUBCOMMAND
              value: "{{ .Values.senzing.subcommand }}"
            - name: SENZING_KAFKA_TOPIC
              value: "{{ .Values.senzing.kafkaTopic }}"
            - name: SENZING_DATA_SOURCE
              value: "{{ .Values.senzing.dataSource }}"
            - name: SENZING_ENTITY_TYPE
              value: "{{ .Values.senzing.entityType }}"
            - name: SENZING_MONITORING_PERIOD
              value: "{{ .Values.senzing.monitoringPeriod }}"
            - name: SENZING_THREADS_PER_PROCESS
              value: "{{ .Values.senzing.threadsPerProcess }}"
            - name: SENZING_LOG_LEVEL
              value: "{{ .Values.senzing.logLevel }}"
            - name: SENZING_DATABASE_URL
              value: "{{ .Values.senzing.databaseUrl }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

