apiVersion: v1
appVersion: "1.0"
description: A wrapper over yum package installer prepared for Senzing installs
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
 - install
name: senzing-yum
sources:
 - https://github.com/Senzing/senzing-yum
version: 1.1.5
