apiVersion: v1
appVersion: "1.0"
description: Performs all of the Senzing initialization requiring "root" authority.
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
name: senzing-init-container
sources:
 - https://github.com/Senzing/docker-init-container
version: 0.1.0
