apiVersion: v1
appVersion: "1.0"
description: A Senzing environment
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
name: senzing-base
sources:
 - https://github.com/Senzing/docker-senzing-base
version: 1.2.0
