'image.repository': "data.dockter.com:5000/senzing/stream-loader"
'image.tag': "latest"
'senzing.subcommand': "kafka"
'senzing.databaseUrl': "mysql://g2:g2@my-mysql-mysql:3306/G2"
'senzing.dataSource': "PEOPLE"
'senzing.entityType': "PEOPLE"
'senzing.kafkaBootstrapServerHost': "my-kafka-kafka"
'senzing.kafkaBootstrapServerPort': 9092
'senzing.kafkaTopic': "senzing-kafka-topic"
'senzing.logLevel': "info"
'senzing.monitoringPeriod': 60
'senzing.optSenzingClaim': "opt-senzing-claim"
'senzing.threadsPerProcess': 4
