apiVersion: v1
appVersion: "1.0"
description: A stream-based loader for Senzing
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
 - kafka
name: senzing-stream-loader
sources:
 - https://github.com/Senzing/stream-loader
version: 1.2.0
