apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "senzing-yum.fullname" . }}
  labels:
    {{- include "senzing-yum.labels" . | nindent 4 }}
  {{- with .Values.deployment.metadata.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.deployment.spec.template.metadata.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.senzing.yumParameters }}
          args:
            {{- toYaml .Values.senzing.yumParameters | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.senzing.acceptEula }}
            - name: "SENZING_ACCEPT_EULA"
              value: {{ .Values.senzing.acceptEula | quote }}
            {{- end }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.rbacEnabled}}
          securityContext:
            privileged: true
          {{- end }}
          {{- if .Values.senzing.persistentVolumeClaim }}
          volumeMounts:
            - name: senzing-storage
              mountPath: /opt/senzing/data
              subPath: senzing-data
            - name: senzing-storage
              mountPath: /etc/opt/senzing
              subPath: senzing-etc
            - name: senzing-storage
              mountPath: /opt/senzing/g2
              subPath: senzing-g2
            - name: senzing-storage
              mountPath: /rpms
              subPath: senzing-rpms
            - name: senzing-storage
              mountPath: /var/opt/senzing
              subPath: senzing-var
          {{- end }}
      initContainers:
        - name: senzing-mount-maker
          image: busybox:1.28
          {{- if .Values.rbacEnabled}}
          securityContext:
            privileged: true
          {{- end }}
          {{- if .Values.senzing.persistentVolumeClaim }}
          volumeMounts:
            - name:  senzing-storage
              mountPath: /opt/senzing
          {{- end }}
      restartPolicy: Never
      {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ template "senzing-yum.fullname" . }}
      {{- end }}
      volumes:
        {{- if .Values.senzing.persistentVolumeClaim }}
        - name: senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.persistentVolumeClaim }}
        {{- end }}
        {{- if .Values.senzing.senzingDataClaim }}
        - name: senzing-data-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.senzingDataClaim }}
        {{- end }}
        {{- if .Values.senzing.senzingEtcClaim }}
        - name: senzing-etc-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.senzingEtcClaim }}
        {{- end }}
        {{- if .Values.senzing.senzingG2Claim }}
        - name: senzing-g2-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.senzingG2Claim }}
        {{- end }}
        {{- if .Values.senzing.senzingVarClaim }}
        - name: senzing-var-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.senzingVarClaim }}
        {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
