apiVersion: v1
name: phpmyadmin
version: 2.0.6
appVersion: 4.8.5
description: phpMyAdmin, an mysql administration frontend
keywords:
- mysql
- phpmyadmin
home: https://www.phpmyadmin.net/
icon: https://bitnami.com/assets/stacks/phpmyadmin/img/phpmyadmin-stack-2.0.334.png
sources:
- https://github.com/bitnami/bitnami-docker-phpmyadmin
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
