apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "senzing-init-container.fullname" . }}
  labels:
    {{ include "senzing-init-container.labels" . }}
  {{- with .Values.deployment.metadata.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.deployment.spec.template.metadata.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- if .Values.senzing.debug }}
            - name: "SENZING_DEBUG"
              value: "{{ .Values.senzing.debug }}"
            {{- end }}
            {{- if .Values.senzing.databaseUrl }}
            - name: SENZING_DATABASE_URL
              value: "{{ .Values.senzing.databaseUrl }}"
            {{- end }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.rbacEnabled}}
          securityContext:
            privileged: true
          {{- end }}
          {{- if .Values.senzing.persistentVolumeClaim }}
          volumeMounts:
            - name: senzing-storage
              mountPath: /opt/senzing/data
              subPath: senzing-data/1.0.0
            - name: senzing-storage
              mountPath: /etc/opt/senzing
              subPath: senzing-etc
            - name: senzing-storage
              mountPath: /opt/senzing/g2
              subPath: senzing-g2
            - name: senzing-storage
              mountPath: /var/opt/senzing
              subPath: senzing-var
            - name: senzing-storage
              mountPath: /opt/IBM
              subPath: senzing-db2-drivers
          {{- end }}
      restartPolicy: Never
      {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ template "senzing-init-container.fullname" . }}
      {{- end }}
      {{- if .Values.senzing.persistentVolumeClaim }}
      volumes:
        - name: senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.persistentVolumeClaim }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
