apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "senzing-base.fullname" . }}
  labels:
    {{- include "senzing-base.labels" . | nindent 4 }}
  {{- with .Values.deployment.metadata.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "senzing-base.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "senzing-base.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.deployment.spec.template.metadata.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      initContainers:
        - name: senzing-mount-maker
          image: busybox:1.28
          {{- if .Values.rbacEnabled}}
          securityContext:
            privileged: true
          {{- end }}
          {{- if .Values.senzing.persistentVolumeClaim }}
          volumeMounts:
            - name:  senzing-storage
              mountPath: /opt/senzing
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.senzing.args }}
          args:
            {{- toYaml .Values.senzing.args | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.rbacEnabled}}
          securityContext:
            privileged: true
          {{- end }}
          {{- if .Values.senzing.persistentVolumeClaim }}
          volumeMounts:
            - name: senzing-storage
              mountPath: /opt/senzing/data
              subPath: senzing-data/2.0.0
            - name: senzing-storage
              mountPath: /etc/opt/senzing
              subPath: senzing-etc
            - name: senzing-storage
              mountPath: /opt/senzing/g2
              subPath: senzing-g2
            - name: senzing-storage
              mountPath: /var/opt/senzing
              subPath: senzing-var
            - name: senzing-storage
              mountPath: /opt/IBM
              subPath: senzing-db2-drivers
          {{- end }}
          {{- if .Values.senzing.optSenzingClaim }}
          volumeMounts:
            - name: senzing-storage
              mountPath: /opt/senzing
          {{- end }}
      {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ template "senzing-base.fullname" . }}
      {{- end }}
      {{- if .Values.senzing.persistentVolumeClaim }}
      volumes:
        - name: senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.persistentVolumeClaim }}
      {{- end }}
      {{- if .Values.senzing.optSenzingClaim }}
      volumes:
        - name: senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.optSenzingClaim }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
